### ISSUE TITLE
Can't find phaser-tiled 2.0.0

### ISSUE THREAD

**Issue by contextlimit** [englercj/lttp-phaser#2]
Hey, it seems like package.json is referencing a version of phaser-tiled that doesn't exist. I've tried with 1.4.1 too and I run into a bunch of other issues with font resources. Is there a version of lttp that is known to be working? Cheers!

**Comment by englercj** [comment]
Not really in this repo, this was my development spot.

Most of the versions of my own packages it uses are unreleased as I was developing them for this. I plan to get back into this shortly and I'll update you when I have a "working" version.

Even the version of Phaser this used was a fork I made that updated it to use pixi v3. So it isn't something you can clone and run right now.

**Comment by contextlimit** [comment]
Hey thanks for the reply @englercj 
Cool well if you don't mind zipping up your package and sending it, I could create a dev branch that "works" so that others can possibly contribute :)
Let me know eric@muyser.com
Cheers

**Comment by contextlimit** [comment]
Otherwise perhaps it would be nice to add a disclaimer to the README. The README, and specifically this sentence is misleading, "but you can always run the current state of master by installing Node.js, and running the following:"
Nobody would suspect they can't actually get master running in its current state. That's not something that should be encouraged in open source either :)

**Comment by englercj** [comment]
I kept the branches working for a long time, but eventually fell out of the practice because no one ever wanted to contribute :)

If you are actually looking to contribute I will do my best to get this working ASAP so you can.

**Comment by englercj** [comment]
I'm also converting it to use git LFS which may include some force pushes that invalidate any clone you may have. I'd wait until I post here again to start working on anything.

**Comment by englercj** [comment]
Ok, after a bunch of work I finally have the project running again.

I've also updated the readme with the correct procedure to start developing the project:
https://github.com/englercj/lttp-phaser#building-and-running-the-game

**Comment by contextlimit** [comment]
Sweet. I've already started on a game but going to check this out!

**Comment by contextlimit** [comment]
Thanks for the quick response

**Comment by contextlimit** [comment]
Cool. It works. Amazing! This as far as it's suppose to go right?

![image](https://cloud.githubusercontent.com/assets/156768/13729921/dc0323e8-e8fd-11e5-904d-705f28e4129a.png)

**Comment by contextlimit** [comment]
How do I open these JSON level files in Tiled?

**Comment by englercj** [comment]
You can walk out of the house, to open the level files launch Tiled, select Open, select the json level file.

**Comment by englercj** [comment]
Also just fixed that overlay showing, as well as some other minor things.

**Comment by contextlimit** [comment]
Oh my god, I didn't realize there was a dropdown to choose the type of file to open. I'm not sure I've seen that before, rarely.. Thanks man!

I couldn't walk out of the door but I'll try again

**Comment by englercj** [comment]
Make sure you are on the latest, I've been making changes/fixes every night.
