### ISSUE TITLE
How to render TMX How to render TMX in ThreeJs plane?

### ISSUE THREAD

**Issue by c9c9** [englercj/lttp-phaser#9]
Hi.
I have studied your project for more than a month.I tried to run the code but it didn't work. Would you give a complete example code about how to render TMX How to render TMX in ThreeJs plane?

**Comment by englercj** [comment]
I haven't used three.js in this project in a really long time. Around 6 years ago I [did this](https://stackoverflow.com/questions/13516990/render-tmx-map-on-threejs-plane).

More recently I made a generic webgl renderer for tiled maps: https://github.com/englercj/gl-tiled

**Comment by c9c9** [comment]
Thank you very much.
